### ISSUE TITLE
Validation concept

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptrValidation#15]
* I'd strike case IV.2 (very similar to I) but use case IV to check whether optimal designs react as expected to changes in alpha/beta (default: .025/.9; also check .05/.9 and .025/.8).

* II.2 is meant to take the continuous prior conditional on the null hypothesis or just the point null? I'd prefer the former!

**Comment by MatheMax** [comment]
oh, just saw this now.
I agree with the both points and will implement this.
But isn't .8 the usual default for power?

**Comment by kkmann** [comment]
I'd argue its too small ;) anyway doesn't matter we need to make sure it works for .8 and .9. @MatheMax with III, I feel we really need a plot with all 'converging' designs in one graph, right?
