### ISSUE TITLE
Make things understandable

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptrValidation#24]
In order to improve the presentation we agreed to the following points

- [x] we need a rationale for the tolerances in testthat

- [x] in scenario III the "converging" designs should be plotted in one common ggplot

- [x] print all simulated values for error rates with standard error in a respective chunk

- [ ] explain the starting values

**Comment by kkmann** [comment]
I'd just add that it's 'explaining the starting values' might also entail adjusting the a bit - depending on the chosen rationale. Luckily our approach is robust to variations in the starting values - is there a scenario/case covering that already?

**Comment by MatheMax** [comment]
In Scenario III I used the upper bound as starting value and ended up with the same design as in case I.1

**Comment by kkmann** [comment]
think we are done except for #36
