### ISSUE TITLE
implement tests for convergence checking

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptrValidation#35]
@MatheMax we should always check for convergence formally! Not sure how to best do that. ideally directly use the nloptr return status!

cf. problem here

https://kkmann.github.io/adoptrValidation/articles/scenario-II.html#case-ii-2-minimizing-expected-sample-size-under-the-null-hypothesis

**Comment by MatheMax** [comment]
should be checked in all cases now, c.f. #46
