### ISSUE TITLE
validate regularizers?

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptrValidation#39]
We do no longer utilize regularizers. I think it is great that we established that they are not usually required but nevertheless there might be situations where ppl might want to use them. So we should probably validate them as well.

Currently, we have smoothness, n1, and average n2. I'd suggest to start from the same base-design and compute two designs using each regularizer (two strengths). then maybe put everything together in one graph (7 designs ...)?

**Comment by kkmann** [comment]
added it to the index, still needs to be implemented

**Comment by MatheMax** [comment]
done with #45 and #46
