### ISSUE TITLE
no math in GitHub markdown!

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptrValidation#6]
@MatheMax GitHub markdown does not support MathJax - we need to put the validation concept in a separate index.Rmd file to be rendered by pkgdown!

**Comment by kkmann** [comment]
could also use README.Rmd to compile README.md with LaTeX formulas!

**Comment by MatheMax** [comment]
So the "output" of the ReadMe has to be changed from github_document to another one?

**Comment by kkmann** [comment]
?

**Comment by MatheMax** [comment]
Okay, it seems to work, I missunderstood the messages above
